<?php
/**
 *  This is auto generated by PHP5 Tools based on the Database Schema.
 *  Author : PHP5 Tools 1.0
 *  Project : R&G
 *  Last Updated : Mon 09th Mar,2009 09:45 am
 *  Table Name : admin_tab
 */

class Admin
{
	public $id;
	public $username;
	public $password;
	public $status;
	public $last_login_time;
	public $time_;

	//===int(10) unsigned===//
	public function getId(){return $this->id;}
	public function setId($id){$this->id= $id;}

	//===varchar(45)===//
	public function getUsername(){return $this->username;}
	public function setUsername($username){$this->username= $username;}

	//===varchar(45)===//
	public function getPassword(){return $this->password;}
	public function setPassword($password){$this->password= $password;}

	//===varchar(45)===//
	public function getStatus(){return $this->status;}
	public function setStatus($status){$this->status= $status;}

	//===datetime===//
	public function getLast_login_time(){return $this->last_login_time;}
	public function setLast_login_time($last_login_time){$this->last_login_time= $last_login_time;}

	//===timestamp===//
	public function getTime_(){return $this->time_;}
	public function setTime_($time_){$this->time_= $time_;}

}


// Implement class of Admin
class AdminDaoImpl
{
	private $db = null ;

	function __construct() {
		$this->db=new DBConnection();
	}

	/** Save the Admin object in to admin_tab */
	function saveAdmin($admin) {
		$adminIn=new Admin();
		$adminIn=$admin;

		$SQL= sprintf("INSERT INTO admin_tab(username,password,status,last_login_time,time_) VALUES('%s','%s','%s','%s','%s')",
		mysql_real_escape_string($adminIn->getUsername()),mysql_real_escape_string($adminIn->getPassword()),mysql_real_escape_string($adminIn->getStatus()),mysql_real_escape_string($adminIn->getLast_login_time()),mysql_real_escape_string($adminIn->getTime_()));

		$this->db->executeQuery($SQL);
	}


	/** UPDATE THE TABLE admin_tab */
	function updateAdmin($admin) {
		$adminIn=new Admin();
		$adminIn=$admin;

		$SQL= sprintf("UPDATE admin_tab SET username='%s',password='%s',status='%s',last_login_time='%s',time_='%s' WHERE id=%d ",
		mysql_real_escape_string($adminIn->getUsername()),mysql_real_escape_string($adminIn->getPassword()),mysql_real_escape_string($adminIn->getStatus()),mysql_real_escape_string($adminIn->getLast_login_time()),mysql_real_escape_string($adminIn->getTime_()),$adminIn->getId());

		$this->db->executeQuery($SQL);
	}

	function updateAdminPassword($admin) {
		$adminIn=new Admin();
		$adminIn=$admin;

		$SQL= sprintf("UPDATE admin_tab SET password='%s',time_='%s' WHERE id=%d ",
		mysql_real_escape_string($adminIn->getPassword()),mysql_real_escape_string($adminIn->getTime_()),$adminIn->getId());

		$this->db->executeQuery($SQL);
	}

	/** Get All data from the table admin_tab */
	function getAllAdmin() {
		$SQL="SELECT * FROM admin_tab";
		$this->db->executeQuery($SQL);

		$result = array();
		$count = 0;

		while($rs = $this->db->nextRecord())
		{
			$admin = new Admin();
			$admin->setId($rs['id']);
			$admin->setUsername($rs['username']);
			$admin->setPassword($rs['password']);
			$admin->setStatus($rs['status']);
			$admin->setLast_login_time($rs['last_login_time']);
			$admin->setTime_($rs['time_']);
			$result[$count++] = $admin;
		}

		$this->db->closeRs();
		return $result;
	}

	public function getUserNameAndPassword($username,$password) {

		$SQL=sprintf("SELECT * FROM admin_tab WHERE username ='%s' AND password ='%s'",mysql_real_escape_string($username),mysql_real_escape_string($password));

		$this->db->executeQuery($SQL);
			
		$result = array();
		$count = 0;
			
		while($rs = $this->db->nextRecord())
		{
			$admin = new Admin();
			$admin->setId($rs['id']);
			$admin->setUsername($rs['username']);
			$admin->setPassword($rs['password']);
			$admin->setStatus($rs['status']);
			$admin->setLast_login_time($rs['last_login_time']);
			$admin->setTime_($rs['time_']);
			$result[$count++] = $admin;
		}

			
		$this->db->closeRs();
			
		if(count($result) > 0 ) {
			return $result[0];
		}else {
			return null;
		}
	}

	/** GET ONE DATA BY ID FROM THE TABLE admin_tab */
	function getOneAdminById($id) {
		$SQL="SELECT * FROM admin_tab WHERE id = '$id'";
		$this->db->executeQuery($SQL);

		$result = array();
		$count = 0;

		while($rs = $this->db->nextRecord())
		{
			$admin = new Admin();
			$admin->setId($rs['id']);
			$admin->setUsername($rs['username']);
			$admin->setPassword($rs['password']);
			$admin->setStatus($rs['status']);
			$admin->setLast_login_time($rs['last_login_time']);
			$admin->setTime_($rs['time_']);
			$result[$count++] = $admin;
		}

		$this->db->closeRs();
		if(count($result) > 0 ){
			return $result[0];
		}else{
			return null;
		}
	}

	/** GET DATA BY ID, STATUS FROM THE TABLE admin_tab */
	function getAllAdminById_Status($id) {
		$SQL="SELECT * FROM admin_tab WHERE id = '$id' AND status = 'Yes'";
		$this->db->executeQuery($SQL);

		$result = array();
		$count = 0;

		while($rs = $this->db->nextRecord())
		{
			$admin = new Admin();
			$admin->setId($rs['id']);
			$admin->setUsername($rs['username']);
			$admin->setPassword($rs['password']);
			$admin->setStatus($rs['status']);
			$admin->setLast_login_time($rs['last_login_time']);
			$admin->setTime_($rs['time_']);
			$result[$count++] = $admin;
		}

		$this->db->closeRs();
		if(count($result) > 0 ){
			return $result[0];
		}else{
			return null;
		}
	}

	/** Delete value by id from the table admin_tab */
	function deleteAdminById($id) {
		$SQL="DELETE FROM admin_tab WHERE id='$id'";
		$this->db->executeQuery($SQL);

	}
	function __destruct() {
		$this->db->close();
	}

}
?>