<?php
/**
 *  This is auto generated by PHP5 Tools based on the Database Schema.
 *  Author : MahiShimi PHP5 Tools version 1.1
 *  Project : Cambridge
 *  Last Updated : Wed 06th Feb,2013 08:58 am
 *  Table Name : batches
 *  Modifier : This Db tool is currently modified by Maheshwaran Varghese on 10th August 2011
 */

class Batch
{
	public $id;
	public $name;
	public $course_id;
	public $start_date;
	public $end_date;
	public $is_active;
	public $is_deleted;
	public $employee_id;
	public $max_order_no;

	//===int(11)===//
	public function getId(){return $this->id;}
	public function setId($id){$this->id= $id;}

	//===varchar(255)===//
	public function getName(){return $this->name;}
	public function setName($name){$this->name= $name;}

	//===int(11)===//
	public function getCourse_id(){return $this->course_id;}
	public function setCourse_id($course_id){$this->course_id= $course_id;}

	//===datetime===//
	public function getStart_date(){return $this->start_date;}
	public function setStart_date($start_date){$this->start_date= $start_date;}

	//===datetime===//
	public function getEnd_date(){return $this->end_date;}
	public function setEnd_date($end_date){$this->end_date= $end_date;}

	//===tinyint(1)===//
	public function getIs_active(){return $this->is_active;}
	public function setIs_active($is_active){$this->is_active= $is_active;}

	//===tinyint(1)===//
	public function getIs_deleted(){return $this->is_deleted;}
	public function setIs_deleted($is_deleted){$this->is_deleted= $is_deleted;}

	//===varchar(255)===//
	public function getEmployee_id(){return $this->employee_id;}
	public function setEmployee_id($employee_id){$this->employee_id= $employee_id;}

	//=== max_order_no ===//
	public function getMax_order_no(){return $this->max_order_no;}
	public function setMax_order_no($max_order_no){$this->max_order_no= $max_order_no;}

}


// Implement class of Batch
class BatchDaoImpl
{
	private $db = null ;

	function __construct() {
		$this->db=new DBConnection();
	}

	/** SAVE THE Batch OBJECT INTO batches */
	function saveBatch($batch) {
		$batchIn=new Batch();
		$batchIn=$batch;

		$SQL= sprintf("INSERT INTO batches(name,course_id,start_date,end_date,is_active,is_deleted,employee_id) VALUES('%s',%d,'%s','%s',%d,%d,'%s')",
		mysql_real_escape_string($batchIn->getName()),mysql_real_escape_string($batchIn->getCourse_id()),mysql_real_escape_string($batchIn->getStart_date()),mysql_real_escape_string($batchIn->getEnd_date()),mysql_real_escape_string($batchIn->getIs_active()),mysql_real_escape_string($batchIn->getIs_deleted()),mysql_real_escape_string($batchIn->getEmployee_id()));

		$this->db->executeQuery($SQL);

	}


	/** UPDATE THE TABLE batches */
	function updateBatch($batch) {
		$batchIn=new Batch();
		$batchIn=$batch;

		$SQL= sprintf("UPDATE batches SET name='%s',course_id=%d,start_date='%s',end_date='%s',is_active=%d,is_deleted=%d,employee_id='%s' WHERE id=%d ",
		mysql_real_escape_string($batchIn->getName()),mysql_real_escape_string($batchIn->getCourse_id()),mysql_real_escape_string($batchIn->getStart_date()),mysql_real_escape_string($batchIn->getEnd_date()),mysql_real_escape_string($batchIn->getIs_active()),mysql_real_escape_string($batchIn->getIs_deleted()),mysql_real_escape_string($batchIn->getEmployee_id()),$batchIn->getId());

		$this->db->executeQuery($SQL);

	}

	/** GET ALL DATA FROM THE TABLE batches */
	function getAllBatch() {
		$SQL="SELECT * FROM batches";
		$this->db->executeQuery($SQL);

		$result = array();
		$count = 0;

		while($rs = $this->db->nextRecord())
		{
			$batch = new Batch();
			$batch->setId($rs['id']);
			$batch->setName($rs['name']);
			$batch->setCourse_id($rs['course_id']);
			$batch->setStart_date($rs['start_date']);
			$batch->setEnd_date($rs['end_date']);
			$batch->setIs_active($rs['is_active']);
			$batch->setIs_deleted($rs['is_deleted']);
			$batch->setEmployee_id($rs['employee_id']);
			$result[$count++] = $batch;
		}

		$this->db->closeRs();
		return $result;

	}

	/** GET ALL DATA BY STATUS FROM THE TABLE batches */
	function getAllBatchByStatus() {
		$SQL="SELECT * FROM batches WHERE status = 'Yes'";
		$this->db->executeQuery($SQL);

		$result = array();
		$count = 0;

		while($rs = $this->db->nextRecord())
		{
			$batch = new Batch();
			$batch->setId($rs['id']);
			$batch->setName($rs['name']);
			$batch->setCourse_id($rs['course_id']);
			$batch->setStart_date($rs['start_date']);
			$batch->setEnd_date($rs['end_date']);
			$batch->setIs_active($rs['is_active']);
			$batch->setIs_deleted($rs['is_deleted']);
			$batch->setEmployee_id($rs['employee_id']);
			$result[$count++] = $batch;
		}

		$this->db->closeRs();
		return $result;

	}

	/** GET ALL DATA BY ID DESC FROM THE TABLE batches */
	function getAllBatchByIdDesc() {
		$SQL="SELECT * FROM batches ORDER BY id DESC";
		$this->db->executeQuery($SQL);

		$result = array();
		$count = 0;

		while($rs = $this->db->nextRecord())
		{
			$batch = new Batch();
			$batch->setId($rs['id']);
			$batch->setName($rs['name']);
			$batch->setCourse_id($rs['course_id']);
			$batch->setStart_date($rs['start_date']);
			$batch->setEnd_date($rs['end_date']);
			$batch->setIs_active($rs['is_active']);
			$batch->setIs_deleted($rs['is_deleted']);
			$batch->setEmployee_id($rs['employee_id']);
			$result[$count++] = $batch;
		}

		$this->db->closeRs();
		return $result;

	}

	/** GET ONE DATA BY ID FROM THE TABLE batches */
	function getOneBatchById($id) {
		$SQL="SELECT * FROM batches WHERE id = '$id'";
		$this->db->executeQuery($SQL);

		$result = array();
		$count = 0;

		while($rs = $this->db->nextRecord())
		{
			$batch = new Batch();
			$batch->setId($rs['id']);
			$batch->setName($rs['name']);
			$batch->setCourse_id($rs['course_id']);
			$batch->setStart_date($rs['start_date']);
			$batch->setEnd_date($rs['end_date']);
			$batch->setIs_active($rs['is_active']);
			$batch->setIs_deleted($rs['is_deleted']);
			$batch->setEmployee_id($rs['employee_id']);
			$result[$count++] = $batch;
		}

		$this->db->closeRs();
		if(count($result) > 0 ){
			return $result[0];
		}else{
			return null;
		}
	}

	/** GET DATA BY ID, STATUS FROM THE TABLE batches */
	function getAllBatchById_Status($id) {
		$SQL="SELECT * FROM batches WHERE id = '$id' AND status = 'Yes'";
		$this->db->executeQuery($SQL);

		$result = array();
		$count = 0;

		while($rs = $this->db->nextRecord())
		{
			$batch = new Batch();
			$batch->setId($rs['id']);
			$batch->setName($rs['name']);
			$batch->setCourse_id($rs['course_id']);
			$batch->setStart_date($rs['start_date']);
			$batch->setEnd_date($rs['end_date']);
			$batch->setIs_active($rs['is_active']);
			$batch->setIs_deleted($rs['is_deleted']);
			$batch->setEmployee_id($rs['employee_id']);
			$result[$count++] = $batch;
		}

		$this->db->closeRs();
		if(count($result) > 0 ){
			return $result[0];
		}else{
			return null;
		}
	}

	/** GET LAST RECORD FROM THE TABLE batches */
	function getLastRec($field) {
		$SQL="SELECT * FROM batches ORDER BY $field DESC LIMIT 1";
		$this->db->executeQuery($SQL);

		$result = array();
		$count = 0;

		while($rs = $this->db->nextRecord())
		{
			$batch = new Batch();
			$batch->setId($rs['id']);
			$batch->setName($rs['name']);
			$batch->setCourse_id($rs['course_id']);
			$batch->setStart_date($rs['start_date']);
			$batch->setEnd_date($rs['end_date']);
			$batch->setIs_active($rs['is_active']);
			$batch->setIs_deleted($rs['is_deleted']);
			$batch->setEmployee_id($rs['employee_id']);
			$result[$count++] = $batch;
		}

		$this->db->closeRs();
		if(count($result) > 0 ){
			return $result[0];
		}else{
			return null;
		}
	}

	/** GET DATA ORDER BY ORDER_NO, STATUS FROM THE TABLE batches */
	function getAllBatch_By_Status_ORDER_BY_Order_no() {
		$SQL="SELECT * FROM batches WHERE status = 'Yes' ORDER BY CAST(order_no AS DECIMAL)";
		$this->db->executeQuery($SQL);

		$result = array();
		$count = 0;

		while($rs = $this->db->nextRecord())
		{
			$batch = new Batch();
			$batch->setId($rs['id']);
			$batch->setName($rs['name']);
			$batch->setCourse_id($rs['course_id']);
			$batch->setStart_date($rs['start_date']);
			$batch->setEnd_date($rs['end_date']);
			$batch->setIs_active($rs['is_active']);
			$batch->setIs_deleted($rs['is_deleted']);
			$batch->setEmployee_id($rs['employee_id']);
			$result[$count++] = $batch;
		}

		$this->db->closeRs();
		return $result;

	}

	/** GET DATA BY ID, STATUS ORDER BY ORDER_NO FROM THE TABLE batches */
	function getBatch_By_Id_Status_ORDER_BY_Order_no() {
		$SQL="SELECT * FROM batches WHERE id = '$id' AND status = 'Yes' ORDER BY CAST(order_no AS DECIMAL)";
		$this->db->executeQuery($SQL);

		$result = array();
		$count = 0;

		while($rs = $this->db->nextRecord())
		{
			$batch = new Batch();
			$batch->setId($rs['id']);
			$batch->setName($rs['name']);
			$batch->setCourse_id($rs['course_id']);
			$batch->setStart_date($rs['start_date']);
			$batch->setEnd_date($rs['end_date']);
			$batch->setIs_active($rs['is_active']);
			$batch->setIs_deleted($rs['is_deleted']);
			$batch->setEmployee_id($rs['employee_id']);
			$result[$count++] = $batch;
		}

		$this->db->closeRs();
		if(count($result) > 0 ){
			return $result[0];
		}else{
			return null;
		}
	}

	/** GET DATA MAXIMUM ORDER NO FROM THE TABLE batches */
	function getLastOrderNo() {
		$SQL="SELECT MAX(CAST(order_no AS DECIMAL)) AS max_order_no FROM batches";
		$this->db->executeQuery($SQL);

		$result = array();
		$count = 0;

		while($rs = $this->db->nextRecord())
		{
			$batch = new Batch();
			$batch->setId($rs['id']);
			$batch->setName($rs['name']);
			$batch->setCourse_id($rs['course_id']);
			$batch->setStart_date($rs['start_date']);
			$batch->setEnd_date($rs['end_date']);
			$batch->setIs_active($rs['is_active']);
			$batch->setIs_deleted($rs['is_deleted']);
			$batch->setEmployee_id($rs['employee_id']);
			$batch->setMax_order_no($rs['max_order_no']);
			$result[$count++] = $batch;
		}

		$this->db->closeRs();
		if(count($result) > 0 ){
			return $result[0];
		}else{
			return null;
		}
	}

	function getBatchById_Is_deleted($id) {
		$SQL="SELECT * FROM batches WHERE id = '$id' AND is_deleted = '0'";
		$this->db->executeQuery($SQL);

		$result = array();
		$count = 0;

		while($rs = $this->db->nextRecord())
		{
			$batch = new Batch();
			$batch->setId($rs['id']);
			$batch->setName($rs['name']);
			$batch->setCourse_id($rs['course_id']);
			$batch->setStart_date($rs['start_date']);
			$batch->setEnd_date($rs['end_date']);
			$batch->setIs_active($rs['is_active']);
			$batch->setIs_deleted($rs['is_deleted']);
			$batch->setEmployee_id($rs['employee_id']);
			$result[$count++] = $batch;
		}

		$this->db->closeRs();
		if(count($result) > 0 ){
			return $result[0];
		}else{
			return null;
		}
	}

	/** DELETE VALUE BY ID FROM THE TABLE batches */
	function deleteBatchById($id) {
		$SQL="DELETE FROM batches WHERE id='$id'";
		$this->db->executeQuery($SQL);

	}
	function __destruct() {
		$this->db->close();
	}

}
?>