<?php
/**
 *  This is auto generated by PHP5 Tools based on the Database Schema.
 *  Author : MahiShimi PHP5 Tools version 1.1
 *  Project : Cambridge
 *  Last Updated : Wed 06th Feb,2013 03:19 pm
 *  Table Name : countries
 *  Modifier : This Db tool is currently modified by Maheshwaran Varghese on 10th August 2011
 */

class Countries
{
	public $id;
	public $name;
	public $max_order_no;

	//===int(11)===//
	public function getId(){return $this->id;}
	public function setId($id){$this->id= $id;}

	//===varchar(255)===//
	public function getName(){return $this->name;}
	public function setName($name){$this->name= $name;}

	//=== max_order_no ===//
	public function getMax_order_no(){return $this->max_order_no;}
	public function setMax_order_no($max_order_no){$this->max_order_no= $max_order_no;}

}


// Implement class of Countries
class CountriesDaoImpl
{
	private $db = null ;

	function __construct() {
		$this->db=new DBConnection();
	}

	/** SAVE THE Countries OBJECT INTO countries */
	function saveCountries($countries) {
		$countriesIn=new Countries();
		$countriesIn=$countries;

		$SQL= sprintf("INSERT INTO countries(name) VALUES('%s')",
		mysql_real_escape_string($countriesIn->getName()));

		$this->db->executeQuery($SQL);

	}


	/** UPDATE THE TABLE countries */
	function updateCountries($countries) {
		$countriesIn=new Countries();
		$countriesIn=$countries;

		$SQL= sprintf("UPDATE countries SET name='%s' WHERE id=%d ",
		mysql_real_escape_string($countriesIn->getName()),$countriesIn->getId());

		$this->db->executeQuery($SQL);

	}

	/** GET ALL DATA FROM THE TABLE countries */
	function getAllCountries() {
		$SQL="SELECT * FROM countries";
		$this->db->executeQuery($SQL);

		$result = array();
		$count = 0;

		while($rs = $this->db->nextRecord())
		{
			$countries = new Countries();
			$countries->setId($rs['id']);
			$countries->setName($rs['name']);
			$result[$count++] = $countries;
		}

		$this->db->closeRs();
		return $result;

	}

	/** GET ALL DATA BY STATUS FROM THE TABLE countries */
	function getAllCountriesByStatus() {
		$SQL="SELECT * FROM countries WHERE status = 'Yes'";
		$this->db->executeQuery($SQL);

		$result = array();
		$count = 0;

		while($rs = $this->db->nextRecord())
		{
			$countries = new Countries();
			$countries->setId($rs['id']);
			$countries->setName($rs['name']);
			$result[$count++] = $countries;
		}

		$this->db->closeRs();
		return $result;

	}

	/** GET ALL DATA BY ID DESC FROM THE TABLE countries */
	function getAllCountriesByIdDesc() {
		$SQL="SELECT * FROM countries ORDER BY id DESC";
		$this->db->executeQuery($SQL);

		$result = array();
		$count = 0;

		while($rs = $this->db->nextRecord())
		{
			$countries = new Countries();
			$countries->setId($rs['id']);
			$countries->setName($rs['name']);
			$result[$count++] = $countries;
		}

		$this->db->closeRs();
		return $result;

	}

	/** GET ONE DATA BY ID FROM THE TABLE countries */
	function getOneCountriesById($id) {
		$SQL="SELECT * FROM countries WHERE id = '$id'";
		$this->db->executeQuery($SQL);

		$result = array();
		$count = 0;

		while($rs = $this->db->nextRecord())
		{
			$countries = new Countries();
			$countries->setId($rs['id']);
			$countries->setName($rs['name']);
			$result[$count++] = $countries;
		}

		$this->db->closeRs();
		if(count($result) > 0 ){
			return $result[0];
		}else{
			return null;
		}
	}

	/** GET DATA BY ID, STATUS FROM THE TABLE countries */
	function getAllCountriesById_Status($id) {
		$SQL="SELECT * FROM countries WHERE id = '$id' AND status = 'Yes'";
		$this->db->executeQuery($SQL);

		$result = array();
		$count = 0;

		while($rs = $this->db->nextRecord())
		{
			$countries = new Countries();
			$countries->setId($rs['id']);
			$countries->setName($rs['name']);
			$result[$count++] = $countries;
		}

		$this->db->closeRs();
		if(count($result) > 0 ){
			return $result[0];
		}else{
			return null;
		}
	}

	/** GET LAST RECORD FROM THE TABLE countries */
	function getLastRec($field) {
		$SQL="SELECT * FROM countries ORDER BY $field DESC LIMIT 1";
		$this->db->executeQuery($SQL);

		$result = array();
		$count = 0;

		while($rs = $this->db->nextRecord())
		{
			$countries = new Countries();
			$countries->setId($rs['id']);
			$countries->setName($rs['name']);
			$result[$count++] = $countries;
		}

		$this->db->closeRs();
		if(count($result) > 0 ){
			return $result[0];
		}else{
			return null;
		}
	}

	/** GET DATA ORDER BY ORDER_NO, STATUS FROM THE TABLE countries */
	function getAllCountries_By_Status_ORDER_BY_Order_no() {
		$SQL="SELECT * FROM countries WHERE status = 'Yes' ORDER BY CAST(order_no AS DECIMAL)";
		$this->db->executeQuery($SQL);

		$result = array();
		$count = 0;

		while($rs = $this->db->nextRecord())
		{
			$countries = new Countries();
			$countries->setId($rs['id']);
			$countries->setName($rs['name']);
			$result[$count++] = $countries;
		}

		$this->db->closeRs();
		return $result;

	}

	/** GET DATA BY ID, STATUS ORDER BY ORDER_NO FROM THE TABLE countries */
	function getCountries_By_Id_Status_ORDER_BY_Order_no() {
		$SQL="SELECT * FROM countries WHERE id = '$id' AND status = 'Yes' ORDER BY CAST(order_no AS DECIMAL)";
		$this->db->executeQuery($SQL);

		$result = array();
		$count = 0;

		while($rs = $this->db->nextRecord())
		{
			$countries = new Countries();
			$countries->setId($rs['id']);
			$countries->setName($rs['name']);
			$result[$count++] = $countries;
		}

		$this->db->closeRs();
		if(count($result) > 0 ){
			return $result[0];
		}else{
			return null;
		}
	}

	/** GET DATA MAXIMUM ORDER NO FROM THE TABLE countries */
	function getLastOrderNo() {
		$SQL="SELECT MAX(CAST(order_no AS DECIMAL)) AS max_order_no FROM countries";
		$this->db->executeQuery($SQL);

		$result = array();
		$count = 0;

		while($rs = $this->db->nextRecord())
		{
			$countries = new Countries();
			$countries->setId($rs['id']);
			$countries->setName($rs['name']);
			$countries->setMax_order_no($rs['max_order_no']);
			$result[$count++] = $countries;
		}

		$this->db->closeRs();
		if(count($result) > 0 ){
			return $result[0];
		}else{
			return null;
		}
	}

	/** DELETE VALUE BY ID FROM THE TABLE countries */
	function deleteCountriesById($id) {
		$SQL="DELETE FROM countries WHERE id='$id'";
		$this->db->executeQuery($SQL);

	}
	function __destruct() {
		$this->db->close();
	}

}
?>