<?php
/**
 *  This is auto generated by PHP5 Tools based on the Database Schema.
 *  Author : MahiShimi PHP5 Tools version 1.1
 *  Project : Cambridge
 *  Last Updated : Thu 07th Feb,2013 02:34 pm
 *  Table Name : guardians
 *  Modifier : This Db tool is currently modified by Maheshwaran Varghese on 10th August 2011
 */

class Guardian
{
	public $id;
	public $ward_id;
	public $first_name;
	public $last_name;
	public $relation;
	public $email;
	public $office_phone1;
	public $office_phone2;
	public $mobile_phone;
	public $office_address_line1;
	public $office_address_line2;
	public $city;
	public $state;
	public $country_id;
	public $dob;
	public $occupation;
	public $income;
	public $education;
	public $created_at;
	public $updated_at;
	public $max_order_no;

	//===int(11)===//
	public function getId(){return $this->id;}
	public function setId($id){$this->id= $id;}

	//===int(11)===//
	public function getWard_id(){return $this->ward_id;}
	public function setWard_id($ward_id){$this->ward_id= $ward_id;}

	//===varchar(255)===//
	public function getFirst_name(){return $this->first_name;}
	public function setFirst_name($first_name){$this->first_name= $first_name;}

	//===varchar(255)===//
	public function getLast_name(){return $this->last_name;}
	public function setLast_name($last_name){$this->last_name= $last_name;}

	//===varchar(255)===//
	public function getRelation(){return $this->relation;}
	public function setRelation($relation){$this->relation= $relation;}

	//===varchar(255)===//
	public function getEmail(){return $this->email;}
	public function setEmail($email){$this->email= $email;}

	//===varchar(255)===//
	public function getOffice_phone1(){return $this->office_phone1;}
	public function setOffice_phone1($office_phone1){$this->office_phone1= $office_phone1;}

	//===varchar(255)===//
	public function getOffice_phone2(){return $this->office_phone2;}
	public function setOffice_phone2($office_phone2){$this->office_phone2= $office_phone2;}

	//===varchar(255)===//
	public function getMobile_phone(){return $this->mobile_phone;}
	public function setMobile_phone($mobile_phone){$this->mobile_phone= $mobile_phone;}

	//===varchar(255)===//
	public function getOffice_address_line1(){return $this->office_address_line1;}
	public function setOffice_address_line1($office_address_line1){$this->office_address_line1= $office_address_line1;}

	//===varchar(255)===//
	public function getOffice_address_line2(){return $this->office_address_line2;}
	public function setOffice_address_line2($office_address_line2){$this->office_address_line2= $office_address_line2;}

	//===varchar(255)===//
	public function getCity(){return $this->city;}
	public function setCity($city){$this->city= $city;}

	//===varchar(255)===//
	public function getState(){return $this->state;}
	public function setState($state){$this->state= $state;}

	//===int(11)===//
	public function getCountry_id(){return $this->country_id;}
	public function setCountry_id($country_id){$this->country_id= $country_id;}

	//===date===//
	public function getDob(){return $this->dob;}
	public function setDob($dob){$this->dob= $dob;}

	//===varchar(255)===//
	public function getOccupation(){return $this->occupation;}
	public function setOccupation($occupation){$this->occupation= $occupation;}

	//===varchar(255)===//
	public function getIncome(){return $this->income;}
	public function setIncome($income){$this->income= $income;}

	//===varchar(255)===//
	public function getEducation(){return $this->education;}
	public function setEducation($education){$this->education= $education;}

	//===datetime===//
	public function getCreated_at(){return $this->created_at;}
	public function setCreated_at($created_at){$this->created_at= $created_at;}

	//===datetime===//
	public function getUpdated_at(){return $this->updated_at;}
	public function setUpdated_at($updated_at){$this->updated_at= $updated_at;}

	//=== max_order_no ===//
	public function getMax_order_no(){return $this->max_order_no;}
	public function setMax_order_no($max_order_no){$this->max_order_no= $max_order_no;}

}


// Implement class of Guardian
class GuardianDaoImpl
{
	private $db = null ;

	function __construct() {
		$this->db=new DBConnection();
	}

	/** SAVE THE Guardian OBJECT INTO guardians */
	function saveGuardian($guardian) {
		$guardianIn=new Guardian();
		$guardianIn=$guardian;

		$SQL= sprintf("INSERT INTO guardians(ward_id,first_name,last_name,relation,email,office_phone1,office_phone2,mobile_phone,office_address_line1,office_address_line2,city,state,country_id,dob,occupation,income,education,created_at,updated_at) VALUES(%d,'%s','%s','%s','%s','%s','%s','%s','%s','%s','%s','%s',%d,'%s','%s','%s','%s','%s','%s')",
		mysql_real_escape_string($guardianIn->getWard_id()),mysql_real_escape_string($guardianIn->getFirst_name()),mysql_real_escape_string($guardianIn->getLast_name()),mysql_real_escape_string($guardianIn->getRelation()),mysql_real_escape_string($guardianIn->getEmail()),mysql_real_escape_string($guardianIn->getOffice_phone1()),mysql_real_escape_string($guardianIn->getOffice_phone2()),mysql_real_escape_string($guardianIn->getMobile_phone()),mysql_real_escape_string($guardianIn->getOffice_address_line1()),mysql_real_escape_string($guardianIn->getOffice_address_line2()),mysql_real_escape_string($guardianIn->getCity()),mysql_real_escape_string($guardianIn->getState()),mysql_real_escape_string($guardianIn->getCountry_id()),mysql_real_escape_string($guardianIn->getDob()),mysql_real_escape_string($guardianIn->getOccupation()),mysql_real_escape_string($guardianIn->getIncome()),mysql_real_escape_string($guardianIn->getEducation()),mysql_real_escape_string($guardianIn->getCreated_at()),mysql_real_escape_string($guardianIn->getUpdated_at()));

		$this->db->executeQuery($SQL);

	}


	/** UPDATE THE TABLE guardians */
	function updateGuardian($guardian) {
		$guardianIn=new Guardian();
		$guardianIn=$guardian;

		$SQL= sprintf("UPDATE guardians SET ward_id=%d,first_name='%s',last_name='%s',relation='%s',email='%s',office_phone1='%s',office_phone2='%s',mobile_phone='%s',office_address_line1='%s',office_address_line2='%s',city='%s',state='%s',country_id=%d,dob='%s',occupation='%s',income='%s',education='%s',created_at='%s',updated_at='%s' WHERE id=%d ",
		mysql_real_escape_string($guardianIn->getWard_id()),mysql_real_escape_string($guardianIn->getFirst_name()),mysql_real_escape_string($guardianIn->getLast_name()),mysql_real_escape_string($guardianIn->getRelation()),mysql_real_escape_string($guardianIn->getEmail()),mysql_real_escape_string($guardianIn->getOffice_phone1()),mysql_real_escape_string($guardianIn->getOffice_phone2()),mysql_real_escape_string($guardianIn->getMobile_phone()),mysql_real_escape_string($guardianIn->getOffice_address_line1()),mysql_real_escape_string($guardianIn->getOffice_address_line2()),mysql_real_escape_string($guardianIn->getCity()),mysql_real_escape_string($guardianIn->getState()),mysql_real_escape_string($guardianIn->getCountry_id()),mysql_real_escape_string($guardianIn->getDob()),mysql_real_escape_string($guardianIn->getOccupation()),mysql_real_escape_string($guardianIn->getIncome()),mysql_real_escape_string($guardianIn->getEducation()),mysql_real_escape_string($guardianIn->getCreated_at()),mysql_real_escape_string($guardianIn->getUpdated_at()),$guardianIn->getId());

		$this->db->executeQuery($SQL);

	}

	/** GET ALL DATA FROM THE TABLE guardians */
	function getAllGuardian() {
		$SQL="SELECT * FROM guardians";
		$this->db->executeQuery($SQL);

		$result = array();
		$count = 0;

		while($rs = $this->db->nextRecord())
		{
			$guardian = new Guardian();
			$guardian->setId($rs['id']);
			$guardian->setWard_id($rs['ward_id']);
			$guardian->setFirst_name($rs['first_name']);
			$guardian->setLast_name($rs['last_name']);
			$guardian->setRelation($rs['relation']);
			$guardian->setEmail($rs['email']);
			$guardian->setOffice_phone1($rs['office_phone1']);
			$guardian->setOffice_phone2($rs['office_phone2']);
			$guardian->setMobile_phone($rs['mobile_phone']);
			$guardian->setOffice_address_line1($rs['office_address_line1']);
			$guardian->setOffice_address_line2($rs['office_address_line2']);
			$guardian->setCity($rs['city']);
			$guardian->setState($rs['state']);
			$guardian->setCountry_id($rs['country_id']);
			$guardian->setDob($rs['dob']);
			$guardian->setOccupation($rs['occupation']);
			$guardian->setIncome($rs['income']);
			$guardian->setEducation($rs['education']);
			$guardian->setCreated_at($rs['created_at']);
			$guardian->setUpdated_at($rs['updated_at']);
			$result[$count++] = $guardian;
		}

		$this->db->closeRs();
		return $result;

	}

	/** GET ALL DATA BY STATUS FROM THE TABLE guardians */
	function getAllGuardianByStatus() {
		$SQL="SELECT * FROM guardians WHERE status = 'Yes'";
		$this->db->executeQuery($SQL);

		$result = array();
		$count = 0;

		while($rs = $this->db->nextRecord())
		{
			$guardian = new Guardian();
			$guardian->setId($rs['id']);
			$guardian->setWard_id($rs['ward_id']);
			$guardian->setFirst_name($rs['first_name']);
			$guardian->setLast_name($rs['last_name']);
			$guardian->setRelation($rs['relation']);
			$guardian->setEmail($rs['email']);
			$guardian->setOffice_phone1($rs['office_phone1']);
			$guardian->setOffice_phone2($rs['office_phone2']);
			$guardian->setMobile_phone($rs['mobile_phone']);
			$guardian->setOffice_address_line1($rs['office_address_line1']);
			$guardian->setOffice_address_line2($rs['office_address_line2']);
			$guardian->setCity($rs['city']);
			$guardian->setState($rs['state']);
			$guardian->setCountry_id($rs['country_id']);
			$guardian->setDob($rs['dob']);
			$guardian->setOccupation($rs['occupation']);
			$guardian->setIncome($rs['income']);
			$guardian->setEducation($rs['education']);
			$guardian->setCreated_at($rs['created_at']);
			$guardian->setUpdated_at($rs['updated_at']);
			$result[$count++] = $guardian;
		}

		$this->db->closeRs();
		return $result;

	}

	/** GET ALL DATA BY ID DESC FROM THE TABLE guardians */
	function getAllGuardianByIdDesc() {
		$SQL="SELECT * FROM guardians ORDER BY id DESC";
		$this->db->executeQuery($SQL);

		$result = array();
		$count = 0;

		while($rs = $this->db->nextRecord())
		{
			$guardian = new Guardian();
			$guardian->setId($rs['id']);
			$guardian->setWard_id($rs['ward_id']);
			$guardian->setFirst_name($rs['first_name']);
			$guardian->setLast_name($rs['last_name']);
			$guardian->setRelation($rs['relation']);
			$guardian->setEmail($rs['email']);
			$guardian->setOffice_phone1($rs['office_phone1']);
			$guardian->setOffice_phone2($rs['office_phone2']);
			$guardian->setMobile_phone($rs['mobile_phone']);
			$guardian->setOffice_address_line1($rs['office_address_line1']);
			$guardian->setOffice_address_line2($rs['office_address_line2']);
			$guardian->setCity($rs['city']);
			$guardian->setState($rs['state']);
			$guardian->setCountry_id($rs['country_id']);
			$guardian->setDob($rs['dob']);
			$guardian->setOccupation($rs['occupation']);
			$guardian->setIncome($rs['income']);
			$guardian->setEducation($rs['education']);
			$guardian->setCreated_at($rs['created_at']);
			$guardian->setUpdated_at($rs['updated_at']);
			$result[$count++] = $guardian;
		}

		$this->db->closeRs();
		return $result;

	}

	/** GET ONE DATA BY ID FROM THE TABLE guardians */
	function getOneGuardianById($id) {
		$SQL="SELECT * FROM guardians WHERE ward_id = '$id'";
		$this->db->executeQuery($SQL);

		$result = array();
		$count = 0;

		while($rs = $this->db->nextRecord())
		{
			$guardian = new Guardian();
			$guardian->setId($rs['id']);
			$guardian->setWard_id($rs['ward_id']);
			$guardian->setFirst_name($rs['first_name']);
			$guardian->setLast_name($rs['last_name']);
			$guardian->setRelation($rs['relation']);
			$guardian->setEmail($rs['email']);
			$guardian->setOffice_phone1($rs['office_phone1']);
			$guardian->setOffice_phone2($rs['office_phone2']);
			$guardian->setMobile_phone($rs['mobile_phone']);
			$guardian->setOffice_address_line1($rs['office_address_line1']);
			$guardian->setOffice_address_line2($rs['office_address_line2']);
			$guardian->setCity($rs['city']);
			$guardian->setState($rs['state']);
			$guardian->setCountry_id($rs['country_id']);
			$guardian->setDob($rs['dob']);
			$guardian->setOccupation($rs['occupation']);
			$guardian->setIncome($rs['income']);
			$guardian->setEducation($rs['education']);
			$guardian->setCreated_at($rs['created_at']);
			$guardian->setUpdated_at($rs['updated_at']);
			$result[$count++] = $guardian;
		}

		$this->db->closeRs();
		if(count($result) > 0 ){
			return $result[0];
		}else{
			return null;
		}
	}

	/** GET DATA BY ID, STATUS FROM THE TABLE guardians */
	function getAllGuardianById_Status($id) {
		$SQL="SELECT * FROM guardians WHERE id = '$id' AND status = 'Yes'";
		$this->db->executeQuery($SQL);

		$result = array();
		$count = 0;

		while($rs = $this->db->nextRecord())
		{
			$guardian = new Guardian();
			$guardian->setId($rs['id']);
			$guardian->setWard_id($rs['ward_id']);
			$guardian->setFirst_name($rs['first_name']);
			$guardian->setLast_name($rs['last_name']);
			$guardian->setRelation($rs['relation']);
			$guardian->setEmail($rs['email']);
			$guardian->setOffice_phone1($rs['office_phone1']);
			$guardian->setOffice_phone2($rs['office_phone2']);
			$guardian->setMobile_phone($rs['mobile_phone']);
			$guardian->setOffice_address_line1($rs['office_address_line1']);
			$guardian->setOffice_address_line2($rs['office_address_line2']);
			$guardian->setCity($rs['city']);
			$guardian->setState($rs['state']);
			$guardian->setCountry_id($rs['country_id']);
			$guardian->setDob($rs['dob']);
			$guardian->setOccupation($rs['occupation']);
			$guardian->setIncome($rs['income']);
			$guardian->setEducation($rs['education']);
			$guardian->setCreated_at($rs['created_at']);
			$guardian->setUpdated_at($rs['updated_at']);
			$result[$count++] = $guardian;
		}

		$this->db->closeRs();
		if(count($result) > 0 ){
			return $result[0];
		}else{
			return null;
		}
	}

	/** GET LAST RECORD FROM THE TABLE guardians */
	function getLastRec($field) {
		$SQL="SELECT * FROM guardians ORDER BY $field DESC LIMIT 1";
		$this->db->executeQuery($SQL);

		$result = array();
		$count = 0;

		while($rs = $this->db->nextRecord())
		{
			$guardian = new Guardian();
			$guardian->setId($rs['id']);
			$guardian->setWard_id($rs['ward_id']);
			$guardian->setFirst_name($rs['first_name']);
			$guardian->setLast_name($rs['last_name']);
			$guardian->setRelation($rs['relation']);
			$guardian->setEmail($rs['email']);
			$guardian->setOffice_phone1($rs['office_phone1']);
			$guardian->setOffice_phone2($rs['office_phone2']);
			$guardian->setMobile_phone($rs['mobile_phone']);
			$guardian->setOffice_address_line1($rs['office_address_line1']);
			$guardian->setOffice_address_line2($rs['office_address_line2']);
			$guardian->setCity($rs['city']);
			$guardian->setState($rs['state']);
			$guardian->setCountry_id($rs['country_id']);
			$guardian->setDob($rs['dob']);
			$guardian->setOccupation($rs['occupation']);
			$guardian->setIncome($rs['income']);
			$guardian->setEducation($rs['education']);
			$guardian->setCreated_at($rs['created_at']);
			$guardian->setUpdated_at($rs['updated_at']);
			$result[$count++] = $guardian;
		}

		$this->db->closeRs();
		if(count($result) > 0 ){
			return $result[0];
		}else{
			return null;
		}
	}

	/** GET DATA ORDER BY ORDER_NO, STATUS FROM THE TABLE guardians */
	function getAllGuardian_By_Status_ORDER_BY_Order_no() {
		$SQL="SELECT * FROM guardians WHERE status = 'Yes' ORDER BY CAST(order_no AS DECIMAL)";
		$this->db->executeQuery($SQL);

		$result = array();
		$count = 0;

		while($rs = $this->db->nextRecord())
		{
			$guardian = new Guardian();
			$guardian->setId($rs['id']);
			$guardian->setWard_id($rs['ward_id']);
			$guardian->setFirst_name($rs['first_name']);
			$guardian->setLast_name($rs['last_name']);
			$guardian->setRelation($rs['relation']);
			$guardian->setEmail($rs['email']);
			$guardian->setOffice_phone1($rs['office_phone1']);
			$guardian->setOffice_phone2($rs['office_phone2']);
			$guardian->setMobile_phone($rs['mobile_phone']);
			$guardian->setOffice_address_line1($rs['office_address_line1']);
			$guardian->setOffice_address_line2($rs['office_address_line2']);
			$guardian->setCity($rs['city']);
			$guardian->setState($rs['state']);
			$guardian->setCountry_id($rs['country_id']);
			$guardian->setDob($rs['dob']);
			$guardian->setOccupation($rs['occupation']);
			$guardian->setIncome($rs['income']);
			$guardian->setEducation($rs['education']);
			$guardian->setCreated_at($rs['created_at']);
			$guardian->setUpdated_at($rs['updated_at']);
			$result[$count++] = $guardian;
		}

		$this->db->closeRs();
		return $result;

	}

	/** GET DATA BY ID, STATUS ORDER BY ORDER_NO FROM THE TABLE guardians */
	function getGuardian_By_Id_Status_ORDER_BY_Order_no() {
		$SQL="SELECT * FROM guardians WHERE id = '$id' AND status = 'Yes' ORDER BY CAST(order_no AS DECIMAL)";
		$this->db->executeQuery($SQL);

		$result = array();
		$count = 0;

		while($rs = $this->db->nextRecord())
		{
			$guardian = new Guardian();
			$guardian->setId($rs['id']);
			$guardian->setWard_id($rs['ward_id']);
			$guardian->setFirst_name($rs['first_name']);
			$guardian->setLast_name($rs['last_name']);
			$guardian->setRelation($rs['relation']);
			$guardian->setEmail($rs['email']);
			$guardian->setOffice_phone1($rs['office_phone1']);
			$guardian->setOffice_phone2($rs['office_phone2']);
			$guardian->setMobile_phone($rs['mobile_phone']);
			$guardian->setOffice_address_line1($rs['office_address_line1']);
			$guardian->setOffice_address_line2($rs['office_address_line2']);
			$guardian->setCity($rs['city']);
			$guardian->setState($rs['state']);
			$guardian->setCountry_id($rs['country_id']);
			$guardian->setDob($rs['dob']);
			$guardian->setOccupation($rs['occupation']);
			$guardian->setIncome($rs['income']);
			$guardian->setEducation($rs['education']);
			$guardian->setCreated_at($rs['created_at']);
			$guardian->setUpdated_at($rs['updated_at']);
			$result[$count++] = $guardian;
		}

		$this->db->closeRs();
		if(count($result) > 0 ){
			return $result[0];
		}else{
			return null;
		}
	}

	/** GET DATA MAXIMUM ORDER NO FROM THE TABLE guardians */
	function getLastOrderNo() {
		$SQL="SELECT MAX(CAST(order_no AS DECIMAL)) AS max_order_no FROM guardians";
		$this->db->executeQuery($SQL);

		$result = array();
		$count = 0;

		while($rs = $this->db->nextRecord())
		{
			$guardian = new Guardian();
			$guardian->setId($rs['id']);
			$guardian->setWard_id($rs['ward_id']);
			$guardian->setFirst_name($rs['first_name']);
			$guardian->setLast_name($rs['last_name']);
			$guardian->setRelation($rs['relation']);
			$guardian->setEmail($rs['email']);
			$guardian->setOffice_phone1($rs['office_phone1']);
			$guardian->setOffice_phone2($rs['office_phone2']);
			$guardian->setMobile_phone($rs['mobile_phone']);
			$guardian->setOffice_address_line1($rs['office_address_line1']);
			$guardian->setOffice_address_line2($rs['office_address_line2']);
			$guardian->setCity($rs['city']);
			$guardian->setState($rs['state']);
			$guardian->setCountry_id($rs['country_id']);
			$guardian->setDob($rs['dob']);
			$guardian->setOccupation($rs['occupation']);
			$guardian->setIncome($rs['income']);
			$guardian->setEducation($rs['education']);
			$guardian->setCreated_at($rs['created_at']);
			$guardian->setUpdated_at($rs['updated_at']);
			$guardian->setMax_order_no($rs['max_order_no']);
			$result[$count++] = $guardian;
		}

		$this->db->closeRs();
		if(count($result) > 0 ){
			return $result[0];
		}else{
			return null;
		}
	}

	/** DELETE VALUE BY ID FROM THE TABLE guardians */
	function deleteGuardianById($id) {
		$SQL="DELETE FROM guardians WHERE id='$id'";
		$this->db->executeQuery($SQL);

	}
	function __destruct() {
		$this->db->close();
	}

}
?>