<?php
/**
 *  This is auto generated by PHP5 Tools based on the Database Schema.
 *  Author : MahiShimi PHP5 Tools version 1.1
 *  Project : Cambridge
 *  Last Updated : Wed 06th Feb,2013 03:08 pm
 *  Table Name : student_categories
 *  Modifier : This Db tool is currently modified by Maheshwaran Varghese on 10th August 2011
 */

class Student_Category
{
	public $id;
	public $name;
	public $is_deleted;
	public $max_order_no;

	//===int(11)===//
	public function getId(){return $this->id;}
	public function setId($id){$this->id= $id;}

	//===varchar(255)===//
	public function getName(){return $this->name;}
	public function setName($name){$this->name= $name;}

	//===tinyint(1)===//
	public function getIs_deleted(){return $this->is_deleted;}
	public function setIs_deleted($is_deleted){$this->is_deleted= $is_deleted;}

	//=== max_order_no ===//
	public function getMax_order_no(){return $this->max_order_no;}
	public function setMax_order_no($max_order_no){$this->max_order_no= $max_order_no;}

}


// Implement class of Student_Category
class Student_CategoryDaoImpl
{
	private $db = null ;

	function __construct() {
		$this->db=new DBConnection();
	}

	/** SAVE THE Student_Category OBJECT INTO student_categories */
	function saveStudent_Category($student_category) {
		$student_categoryIn=new Student_Category();
		$student_categoryIn=$student_category;

		$SQL= sprintf("INSERT INTO student_categories(name,is_deleted) VALUES('%s',%d)",
		mysql_real_escape_string($student_categoryIn->getName()),mysql_real_escape_string($student_categoryIn->getIs_deleted()));

		$this->db->executeQuery($SQL);

	}


	/** UPDATE THE TABLE student_categories */
	function updateStudent_Category($student_category) {
		$student_categoryIn=new Student_Category();
		$student_categoryIn=$student_category;

		$SQL= sprintf("UPDATE student_categories SET name='%s',is_deleted=%d WHERE id=%d ",
		mysql_real_escape_string($student_categoryIn->getName()),mysql_real_escape_string($student_categoryIn->getIs_deleted()),$student_categoryIn->getId());

		$this->db->executeQuery($SQL);

	}

	/** GET ALL DATA FROM THE TABLE student_categories */
	function getAllStudent_Category() {
		$SQL="SELECT * FROM student_categories";
		$this->db->executeQuery($SQL);

		$result = array();
		$count = 0;

		while($rs = $this->db->nextRecord())
		{
			$student_category = new Student_Category();
			$student_category->setId($rs['id']);
			$student_category->setName($rs['name']);
			$student_category->setIs_deleted($rs['is_deleted']);
			$result[$count++] = $student_category;
		}

		$this->db->closeRs();
		return $result;

	}

	/** GET ALL DATA BY STATUS FROM THE TABLE student_categories */
	function getAllStudent_CategoryByStatus() {
		$SQL="SELECT * FROM student_categories WHERE status = 'Yes'";
		$this->db->executeQuery($SQL);

		$result = array();
		$count = 0;

		while($rs = $this->db->nextRecord())
		{
			$student_category = new Student_Category();
			$student_category->setId($rs['id']);
			$student_category->setName($rs['name']);
			$student_category->setIs_deleted($rs['is_deleted']);
			$result[$count++] = $student_category;
		}

		$this->db->closeRs();
		return $result;

	}

	/** GET ALL DATA BY ID DESC FROM THE TABLE student_categories */
	function getAllStudent_CategoryByIdDesc() {
		$SQL="SELECT * FROM student_categories ORDER BY id DESC";
		$this->db->executeQuery($SQL);

		$result = array();
		$count = 0;

		while($rs = $this->db->nextRecord())
		{
			$student_category = new Student_Category();
			$student_category->setId($rs['id']);
			$student_category->setName($rs['name']);
			$student_category->setIs_deleted($rs['is_deleted']);
			$result[$count++] = $student_category;
		}

		$this->db->closeRs();
		return $result;

	}

	/** GET ONE DATA BY ID FROM THE TABLE student_categories */
	function getOneStudent_CategoryById($id) {
		$SQL="SELECT * FROM student_categories WHERE id = '$id'";
		$this->db->executeQuery($SQL);

		$result = array();
		$count = 0;

		while($rs = $this->db->nextRecord())
		{
			$student_category = new Student_Category();
			$student_category->setId($rs['id']);
			$student_category->setName($rs['name']);
			$student_category->setIs_deleted($rs['is_deleted']);
			$result[$count++] = $student_category;
		}

		$this->db->closeRs();
		if(count($result) > 0 ){
			return $result[0];
		}else{
			return null;
		}
	}

	/** GET DATA BY ID, STATUS FROM THE TABLE student_categories */
	function getAllStudent_CategoryById_Status($id) {
		$SQL="SELECT * FROM student_categories WHERE id = '$id' AND status = 'Yes'";
		$this->db->executeQuery($SQL);

		$result = array();
		$count = 0;

		while($rs = $this->db->nextRecord())
		{
			$student_category = new Student_Category();
			$student_category->setId($rs['id']);
			$student_category->setName($rs['name']);
			$student_category->setIs_deleted($rs['is_deleted']);
			$result[$count++] = $student_category;
		}

		$this->db->closeRs();
		if(count($result) > 0 ){
			return $result[0];
		}else{
			return null;
		}
	}

	/** GET LAST RECORD FROM THE TABLE student_categories */
	function getLastRec($field) {
		$SQL="SELECT * FROM student_categories ORDER BY $field DESC LIMIT 1";
		$this->db->executeQuery($SQL);

		$result = array();
		$count = 0;

		while($rs = $this->db->nextRecord())
		{
			$student_category = new Student_Category();
			$student_category->setId($rs['id']);
			$student_category->setName($rs['name']);
			$student_category->setIs_deleted($rs['is_deleted']);
			$result[$count++] = $student_category;
		}

		$this->db->closeRs();
		if(count($result) > 0 ){
			return $result[0];
		}else{
			return null;
		}
	}

	/** GET DATA ORDER BY ORDER_NO, STATUS FROM THE TABLE student_categories */
	function getAllStudent_Category_By_Status_ORDER_BY_Order_no() {
		$SQL="SELECT * FROM student_categories WHERE status = 'Yes' ORDER BY CAST(order_no AS DECIMAL)";
		$this->db->executeQuery($SQL);

		$result = array();
		$count = 0;

		while($rs = $this->db->nextRecord())
		{
			$student_category = new Student_Category();
			$student_category->setId($rs['id']);
			$student_category->setName($rs['name']);
			$student_category->setIs_deleted($rs['is_deleted']);
			$result[$count++] = $student_category;
		}

		$this->db->closeRs();
		return $result;

	}

	/** GET DATA BY ID, STATUS ORDER BY ORDER_NO FROM THE TABLE student_categories */
	function getStudent_Category_By_Id_Status_ORDER_BY_Order_no() {
		$SQL="SELECT * FROM student_categories WHERE id = '$id' AND status = 'Yes' ORDER BY CAST(order_no AS DECIMAL)";
		$this->db->executeQuery($SQL);

		$result = array();
		$count = 0;

		while($rs = $this->db->nextRecord())
		{
			$student_category = new Student_Category();
			$student_category->setId($rs['id']);
			$student_category->setName($rs['name']);
			$student_category->setIs_deleted($rs['is_deleted']);
			$result[$count++] = $student_category;
		}

		$this->db->closeRs();
		if(count($result) > 0 ){
			return $result[0];
		}else{
			return null;
		}
	}

	/** GET DATA MAXIMUM ORDER NO FROM THE TABLE student_categories */
	function getLastOrderNo() {
		$SQL="SELECT MAX(CAST(order_no AS DECIMAL)) AS max_order_no FROM student_categories";
		$this->db->executeQuery($SQL);

		$result = array();
		$count = 0;

		while($rs = $this->db->nextRecord())
		{
			$student_category = new Student_Category();
			$student_category->setId($rs['id']);
			$student_category->setName($rs['name']);
			$student_category->setIs_deleted($rs['is_deleted']);
			$student_category->setMax_order_no($rs['max_order_no']);
			$result[$count++] = $student_category;
		}

		$this->db->closeRs();
		if(count($result) > 0 ){
			return $result[0];
		}else{
			return null;
		}
	}

	function getStudent_CategoryById_Is_deleted($id) {
		$SQL="SELECT * FROM student_categories WHERE id = '$id' AND is_deleted = '0'";
		$this->db->executeQuery($SQL);

		$result = array();
		$count = 0;

		while($rs = $this->db->nextRecord())
		{
			$student_category = new Student_Category();
			$student_category->setId($rs['id']);
			$student_category->setName($rs['name']);
			$student_category->setIs_deleted($rs['is_deleted']);
			$result[$count++] = $student_category;
		}

		$this->db->closeRs();
		if(count($result) > 0 ){
			return $result[0];
		}else{
			return null;
		}
	}

	/** DELETE VALUE BY ID FROM THE TABLE student_categories */
	function deleteStudent_CategoryById($id) {
		$SQL="DELETE FROM student_categories WHERE id='$id'";
		$this->db->executeQuery($SQL);

	}
	function __destruct() {
		$this->db->close();
	}

}
?>