<?php

/**
 *  This is auto generated by PHP5 Tools based on the Database Schema.
 *  Author : MahiShimi PHP5 Tools version 1.1
 *  Project : R&G
 *  Last Updated : Sat 20th Aug,2011 05:00 pm
 *  Table Name : user_tab
 *  Modifier : This Db tool is currently modified by Maheshwaran Varghese on 10th August 2011
 */
class User
{
    public $id;
    public $order_no;
    public $code;
    public $username;
    public $password;
    public $data_date;
    public $status;
    public $date_;
    public $max_order_no;

    //===int(10) unsigned===//
    public function getId()
    {
        return $this->id;
    }

    public function setId($id)
    {
        $this->id = $id;
    }

    //===int(10) unsigned===//
    public function getOrder_no()
    {
        return $this->order_no;
    }

    public function setOrder_no($order_no)
    {
        $this->order_no = $order_no;
    }

    //===varchar(45)===//
    public function getCode()
    {
        return $this->code;
    }

    public function setCode($code)
    {
        $this->code = $code;
    }

    //===varchar(150)===//
    public function getUsername()
    {
        return $this->username;
    }

    public function setUsername($username)
    {
        $this->username = $username;
    }

    //===varchar(150)===//
    public function getPassword()
    {
        return $this->password;
    }

    public function setPassword($password)
    {
        $this->password = $password;
    }

    //===date===//
    public function getData_date()
    {
        return $this->data_date;
    }

    public function setData_date($data_date)
    {
        $this->data_date = $data_date;
    }

    //===varchar(45)===//
    public function getStatus()
    {
        return $this->status;
    }

    public function setStatus($status)
    {
        $this->status = $status;
    }

    //===timestamp===//
    public function getDate_()
    {
        return $this->date_;
    }

    public function setDate_($date_)
    {
        $this->date_ = $date_;
    }

    //=== max_order_no ===//
    public function getMax_order_no()
    {
        return $this->max_order_no;
    }

    public function setMax_order_no($max_order_no)
    {
        $this->max_order_no = $max_order_no;
    }

}


// Implement class of User
class UserDaoImpl
{
    private $db = null;

    function __construct()
    {
        $this->db = new DBConnection();
    }

    /** SAVE THE User OBJECT INTO user_tab */
    function saveUser($user)
    {
        $userIn = new User();
        $userIn = $user;

        $SQL = sprintf("INSERT INTO user_tab(order_no,code,username,password,data_date,status,date_) VALUES(%d,'%s','%s','%s','%s','%s','%s')",
            mysql_real_escape_string($userIn->getOrder_no()), mysql_real_escape_string($userIn->getCode()), mysql_real_escape_string($userIn->getUsername()), mysql_real_escape_string($userIn->getPassword()), mysql_real_escape_string($userIn->getData_date()), mysql_real_escape_string($userIn->getStatus()), mysql_real_escape_string($userIn->getDate_()));

        $this->db->executeQuery($SQL);
        return mysql_insert_id();
    }


    /** UPDATE THE TABLE user_tab */
    function updateUser($user)
    {
        $userIn = new User();
        $userIn = $user;

        $SQL = sprintf("UPDATE user_tab SET order_no=%d,code='%s',username='%s',password='%s',data_date='%s',status='%s',date_='%s' WHERE id=%d ",
            mysql_real_escape_string($userIn->getOrder_no()), mysql_real_escape_string($userIn->getCode()), mysql_real_escape_string($userIn->getUsername()), mysql_real_escape_string($userIn->getPassword()), mysql_real_escape_string($userIn->getData_date()), mysql_real_escape_string($userIn->getStatus()), mysql_real_escape_string($userIn->getDate_()), $userIn->getId());

        $this->db->executeQuery($SQL);

    }

    /** GET ALL DATA FROM THE TABLE user_tab */
    function getAllUser()
    {
        $SQL = "SELECT * FROM user_tab";
        $this->db->executeQuery($SQL);

        $result = array();
        $count = 0;

        while ($rs = $this->db->nextRecord()) {
            $user = new User();
            $user->setId($rs['id']);
            $user->setOrder_no($rs['order_no']);
            $user->setCode($rs['code']);
            $user->setUsername($rs['username']);
            $user->setPassword($rs['password']);
            $user->setData_date($rs['data_date']);
            $user->setStatus($rs['status']);
            $user->setDate_($rs['date_']);
            $result[$count++] = $user;
        }

        $this->db->closeRs();
        return $result;

    }

    /** GET ALL DATA BY STATUS FROM THE TABLE user_tab */
    function getAllUserByStatus()
    {
        $SQL = "SELECT * FROM user_tab WHERE status = 'Yes'";
        $this->db->executeQuery($SQL);

        $result = array();
        $count = 0;

        while ($rs = $this->db->nextRecord()) {
            $user = new User();
            $user->setId($rs['id']);
            $user->setOrder_no($rs['order_no']);
            $user->setCode($rs['code']);
            $user->setUsername($rs['username']);
            $user->setPassword($rs['password']);
            $user->setData_date($rs['data_date']);
            $user->setStatus($rs['status']);
            $user->setDate_($rs['date_']);
            $result[$count++] = $user;
        }

        $this->db->closeRs();
        return $result;

    }

    /** GET ALL DATA BY ID DESC FROM THE TABLE user_tab */
    function getAllUserByIdDesc()
    {
        $SQL = "SELECT * FROM user_tab ORDER BY id DESC";
        $this->db->executeQuery($SQL);

        $result = array();
        $count = 0;

        while ($rs = $this->db->nextRecord()) {
            $user = new User();
            $user->setId($rs['id']);
            $user->setOrder_no($rs['order_no']);
            $user->setCode($rs['code']);
            $user->setUsername($rs['username']);
            $user->setPassword($rs['password']);
            $user->setData_date($rs['data_date']);
            $user->setStatus($rs['status']);
            $user->setDate_($rs['date_']);
            $result[$count++] = $user;
        }

        $this->db->closeRs();
        return $result;

    }

    /** GET ONE DATA BY ID FROM THE TABLE user_tab */
    function getOneUserById($id)
    {
        $SQL = "SELECT * FROM user_tab WHERE id = '$id'";
        $this->db->executeQuery($SQL);

        $result = array();
        $count = 0;

        while ($rs = $this->db->nextRecord()) {
            $user = new User();
            $user->setId($rs['id']);
            $user->setOrder_no($rs['order_no']);
            $user->setCode($rs['code']);
            $user->setUsername($rs['username']);
            $user->setPassword($rs['password']);
            $user->setData_date($rs['data_date']);
            $user->setStatus($rs['status']);
            $user->setDate_($rs['date_']);
            $result[$count++] = $user;
        }

        $this->db->closeRs();
        if (count($result) > 0) {
            return $result[0];
        } else {
            return null;
        }
    }

    /** GET DATA BY ID, STATUS FROM THE TABLE user_tab */
    function getAllUserById_Status($id)
    {
        $SQL = "SELECT * FROM user_tab WHERE id = '$id' AND status = 'Yes'";
        $this->db->executeQuery($SQL);

        $result = array();
        $count = 0;

        while ($rs = $this->db->nextRecord()) {
            $user = new User();
            $user->setId($rs['id']);
            $user->setOrder_no($rs['order_no']);
            $user->setCode($rs['code']);
            $user->setUsername($rs['username']);
            $user->setPassword($rs['password']);
            $user->setData_date($rs['data_date']);
            $user->setStatus($rs['status']);
            $user->setDate_($rs['date_']);
            $result[$count++] = $user;
        }

        $this->db->closeRs();
        if (count($result) > 0) {
            return $result[0];
        } else {
            return null;
        }
    }

    /** GET LAST RECORD FROM THE TABLE user_tab */
    function getLastRec($field)
    {
        $SQL = "SELECT * FROM user_tab ORDER BY $field DESC LIMIT 1";
        $this->db->executeQuery($SQL);

        $result = array();
        $count = 0;

        while ($rs = $this->db->nextRecord()) {
            $user = new User();
            $user->setId($rs['id']);
            $user->setOrder_no($rs['order_no']);
            $user->setCode($rs['code']);
            $user->setUsername($rs['username']);
            $user->setPassword($rs['password']);
            $user->setData_date($rs['data_date']);
            $user->setStatus($rs['status']);
            $user->setDate_($rs['date_']);
            $result[$count++] = $user;
        }

        $this->db->closeRs();
        if (count($result) > 0) {
            return $result[0];
        } else {
            return null;
        }
    }

    /** GET DATA ORDER BY ORDER_NO, STATUS FROM THE TABLE user_tab */
    function getAllUser_By_Status_ORDER_BY_Order_no()
    {
        $SQL = "SELECT * FROM user_tab WHERE status = 'Yes' ORDER BY CAST(order_no AS DECIMAL)";
        $this->db->executeQuery($SQL);

        $result = array();
        $count = 0;

        while ($rs = $this->db->nextRecord()) {
            $user = new User();
            $user->setId($rs['id']);
            $user->setOrder_no($rs['order_no']);
            $user->setCode($rs['code']);
            $user->setUsername($rs['username']);
            $user->setPassword($rs['password']);
            $user->setData_date($rs['data_date']);
            $user->setStatus($rs['status']);
            $user->setDate_($rs['date_']);
            $result[$count++] = $user;
        }

        $this->db->closeRs();
        return $result;

    }

    /** GET DATA BY ID, STATUS ORDER BY ORDER_NO FROM THE TABLE user_tab */
    function getUser_By_Id_Status_ORDER_BY_Order_no()
    {
        $SQL = "SELECT * FROM user_tab WHERE id = '$id' AND status = 'Yes' ORDER BY CAST(order_no AS DECIMAL)";
        $this->db->executeQuery($SQL);

        $result = array();
        $count = 0;

        while ($rs = $this->db->nextRecord()) {
            $user = new User();
            $user->setId($rs['id']);
            $user->setOrder_no($rs['order_no']);
            $user->setCode($rs['code']);
            $user->setUsername($rs['username']);
            $user->setPassword($rs['password']);
            $user->setData_date($rs['data_date']);
            $user->setStatus($rs['status']);
            $user->setDate_($rs['date_']);
            $result[$count++] = $user;
        }

        $this->db->closeRs();
        if (count($result) > 0) {
            return $result[0];
        } else {
            return null;
        }
    }

    /** GET DATA MAXIMUM ORDER NO FROM THE TABLE user_tab */
    function getLastOrderNo()
    {
        $SQL = "SELECT MAX(CAST(order_no AS DECIMAL)) AS max_order_no FROM user_tab";
        $this->db->executeQuery($SQL);

        $result = array();
        $count = 0;

        while ($rs = $this->db->nextRecord()) {
            $user = new User();
            $user->setId($rs['id']);
            $user->setOrder_no($rs['order_no']);
            $user->setCode($rs['code']);
            $user->setUsername($rs['username']);
            $user->setPassword($rs['password']);
            $user->setData_date($rs['data_date']);
            $user->setStatus($rs['status']);
            $user->setDate_($rs['date_']);
            $user->setMax_order_no($rs['max_order_no']);
            $result[$count++] = $user;
        }

        $this->db->closeRs();
        if (count($result) > 0) {
            return $result[0];
        } else {
            return null;
        }
    }

    function getUser_LIKE_code_username($str)
    {
        $SQL = "SELECT * FROM user_tab WHERE (code LIKE '%$str%' OR username LIKE '%$str%') AND status = 'Yes' ORDER BY CAST(order_no AS DECIMAL)";
        $this->db->executeQuery($SQL);

        $result = array();
        $count = 0;

        while ($rs = $this->db->nextRecord()) {
            $user = new User();
            $user->setId($rs['id']);
            $user->setOrder_no($rs['order_no']);
            $user->setCode($rs['code']);
            $user->setUsername($rs['username']);
            $user->setPassword($rs['password']);
            $user->setData_date($rs['data_date']);
            $user->setStatus($rs['status']);
            $user->setDate_($rs['date_']);
            $user->setMax_order_no($rs['max_order_no']);
            $result[$count++] = $user;
        }

        $this->db->closeRs();
        if (count($result) > 0) {
            return $result;
        } else {
            return null;
        }
    }

    public function getUser_By_Username_Password($username, $password)
    {

        $SQL = sprintf("SELECT * FROM user_tab WHERE username='%s' AND password='%s' AND status='%s'", mysql_real_escape_string($username), mysql_real_escape_string($password), "Yes");

        $this->db->executeQuery($SQL);

        $result = array();
        $count = 0;

        while ($rs = $this->db->nextRecord()) {
            $user = new User();
            $user->setId($rs['id']);
            $user->setOrder_no($rs['order_no']);
            $user->setCode($rs['code']);
            $user->setUsername($rs['username']);
            $user->setPassword($rs['password']);
            $user->setData_date($rs['data_date']);
            $user->setStatus($rs['status']);
            $user->setDate_($rs['date_']);
            $user->setMax_order_no($rs['max_order_no']);
            $result[$count++] = $user;
        }


        $this->db->closeRs();

        if (count($result) > 0) {
            return $result[0];
        } else {
            return null;
        }
    }

    function getUser_By_Username($username)
    {
        $SQL = "SELECT * FROM user_tab WHERE username='$username' AND status = 'Yes'";
        $this->db->executeQuery($SQL);

        $result = array();
        $count = 0;

        while ($rs = $this->db->nextRecord()) {
            $user = new User();
            $user->setId($rs['id']);
            $user->setOrder_no($rs['order_no']);
            $user->setCode($rs['code']);
            $user->setUsername($rs['username']);
            $user->setPassword($rs['password']);
            $user->setData_date($rs['data_date']);
            $user->setStatus($rs['status']);
            $user->setDate_($rs['date_']);
            $user->setMax_order_no($rs['max_order_no']);
            $result[$count++] = $user;
        }

        $this->db->closeRs();
        if (count($result) > 0) {
            return $result;
        } else {
            return null;
        }
    }

    /** DELETE VALUE BY ID FROM THE TABLE user_tab */
    function deleteUserById($id)
    {
        $SQL = "DELETE FROM user_tab WHERE id='$id'";
        $this->db->executeQuery($SQL);

    }

    function __destruct()
    {
        $this->db->close();
    }

}

?>